config/routes.rb
Rails.application.routes.draw do
  jsonapi_resources :rfaapi
  jsonapi_resources :location
  jsonapi_resources :commodity
  jsonapi_resources :online

  resources :non_confidences
  resources :rule_proposals
  resources :categories

  resources :trade_runs do
    patch :update_traderun_location, on: :member
  end
  resources :milk_runs
  resources :bots do
  resources :giveaways, only: %i[new show create edit update destroy]
    patch 'toggle_online', on: :member
  end
  resources :trade_sessions
  
  mount ActionCable.server => "/cable"

  constraints subdomain: "sos" do
    get "/" => "web#roadside_assistance"
   end

  resources :articles
  resources :departments do
    resources :users, only: :index
  end

  namespace :api do
    namespace :v1 do
      jsonapi_resources :userships
      resources :star_bitizen_races, only: [:index]
    end
  end




  resources :users, only: [:edit, :update]

  resources :positions
  resources :rules
  resources :user_position_histories
  resources :user_positions
  #resources :votes
  resources :position_nominations
  resources :org_roles
  resources :guildstones
  resources :locations
  resources :tasks
  resources :userships
  resources :manufacturers
  resources :event_records
  resources :event_teams
  resources :event_users
  resources :event_series
  resources :teams
  resources :events
  resources :ships
  resources :rfas
  resources :reviews
  resources :rfa_products
  resources :commodities
  resources :rewards
  resources :control_points
  resources :badges
  resources :user_badges
  resources :categories
  resources :rule_proposals
  resources :messages


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: 'users/sessions' }
  # Defines the root path route ("/")
   
  root 'welcome#index', :constraints => { :subdomain => "ctd" }
  get 'desktop', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'bootup', to: 'desktop#bootup', :constraints => { :subdomain => "ctd" }
  # get 'rfas', to: 'rfas#index'
  get 'conquest', to: 'conquest#index', :constraints => { :subdomain => "ctd" }

  resource :conquest do
    get 'staff', to: 'conquest#staff', :constraints => { :subdomain => "ctd" }
    get 'staff_edit', to: 'conquest#staff_edit', :constraints => { :subdomain => "ctd" }
  end

  post 'staff_code', to: 'conquest#staff_code',  as: :staff_code, :constraints => { :subdomain => "ctd" }
  get 'ship_components', to: 'ship_components#index'
  get 'conquest_event', to: 'conquest#show', :constraints => { :subdomain => "ctd" }
  get 'clear_conquest_records', to: 'event_records#clear_control_points'
  get 'stop_conquest', to: 'control_points#stop_conquest', :constraints => { :subdomain => "ctd" }
  get 'capture_conquest', to: 'control_points#capture_conquest', :constraints => { :subdomain => "ctd" }
  get 'conquest_overlay', to: 'conquest#overlay'
  get 'cargo_manifest', to: 'cargo_manifest#welcome', :constraints => { :subdomain => "ctd" }
  get 'website_manager', to: 'website_manager#welcome'
  get 'my_hangar', to: 'my_hangar#index'
  get 'start_my_hangar', to: 'tasks#start_my_hangar'
  get 'my_hangar_import', to: 'hangardump#index'
  get 'my_hangar_add', to: 'my_hangar#add'
  get 'my_hangar_manage', to: 'my_hangar#manage'
  get 'my_hangar_all_fleet', to: 'my_hangar#all_fleet'
  get 'my_hangar_all_fleet_remove', to: 'my_hangar#all_fleet_remove'
  get 'my_hangar_destroy', to: 'my_hangar#clear_ships'
  get 'my_badges', to: 'badges#my_badges'
  get 'clear_memos', to: 'tasks#clear_memos'
  get 'my_hangar_view', to: 'my_hangar#view'
  get 'fleet_view', to: 'my_hangar#fleet_view'
  get 'users', to: 'desktop#users'
  get 'all_users', to: 'users#all_users'
  get 'roadside_assistance', to: 'web#roadside_assistance'
  get 'current_review', to: 'web#current_review'
  get 'rfa_location', to: 'web#show'
  get 'ship_view', to: 'desktop#ship_view_switch'
  get 'select_ship', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'apply_role', to: 'guildstones#apply_role'
  #get 'vote', to: 'guildstones#vote'
  get 'killall', to:'tasks#killall'
  get 'start_guildstone', to:'tasks#start_guildstone'
  get 'guildstone_start_asl', to: 'guildstones#guildstone_start_asl'
  get 'guildstone_org_chart', to: 'guildstones#open_org_chart'
  get 'guildstone_all_applications', to: 'guildstones#all_applications'
  get 'guildstone_all_nominations', to: 'guildstones#all_nominations'
  
  get 'start_rfa_manager', to: 'tasks#start_rfa_manager'
  get 'rfas_online', to: 'rfas#online'
  get 'start_shell', to: 'tasks#start_shell'
  get 'start_codex', to: 'tasks#start_codex'
  post 'vim_command', to: 'vim#vim_command'

  get 'start_bot_manager', to: 'tasks#start_bot_manager'
  get 'start_asl', to: 'tasks#start_asl'
  get 'codex_timeline', to: 'codex#timeline'
  get 'codex_article', to: 'codex#article'
  get 'codex_data_processor', to: 'codex#codex_data_processor'
  get 'codex_create_article', to: 'codex#create_article'
  get 'codex_edit_article', to: 'codex#edit_article'
  get 'codex_show_article', to: 'codex#show_article'
  get 'codex_back_article', to: 'codex#back_article'
  get 'codex_find_article', to: 'codex#find_article'
  get 'codex_dossier', to: 'codex#create_dossier'
  get 'verify_username', to: 'codex#verify_username'
  get '/invite/:id', to: 'codex#invite', as: 'invite'
  post '/event_join', to: 'codex#event_join', as: 'event_join'



  get 'close_find_window', to: 'codex#close_find_window'
  get 'close_codex_window', to: 'codex#close_codex_window'
  get 'join_event', to: 'event_users#join'
  get 'leave_event', to: 'event_users#leave'
  get 'open_event', to: 'events#open_event'
  get 'command', to: 'shell#command_entry'
  get 'acu_command', to: 'shell#acu_command_entry'
  get 'traderun_command', to: 'shell#traderun_command_entry'
  get 'start_location_manager', to:'tasks#start_location_manager'
  get 'start_ship_manager', to:'tasks#start_ship_manager'
  get 'rsi_user_list', to: 'desktop#rsi_user_list'
  get 'all_user_list', to: 'tasks#state_all_users'
  get 'root_user_list', to: 'tasks#state_root_users'
  get 'twitch_user_list', to: 'tasks#state_twitch_users'
  get 'discord_user_list', to: 'tasks#state_discord_users'
  get 'state_positions', to: 'tasks#state_positions'
  get 'all_state_positions', to: 'tasks#all_state_positions'
  get 'state_user_positions', to: 'tasks#state_user_positions'
  get 'initiate_ship_modal', to: 'tasks#state_ship_modal'
  get 'state_rules', to: 'tasks#state_rules'
  get 'filter_state', to: 'tasks#filter_state'
  get 'state_location_wizard', to: 'tasks#state_location_wizard'

  get 'state_location_edit', to: 'tasks#state_location_edit'
  get 'state_location_subitem', to:'tasks#state_location_subitem'
  get 'state_location_mainitem', to:'tasks#state_location_mainitem'
  get 'close_state_window', to: 'tasks#close_state_window'
  get 'close_last_window', to: 'tasks#close_last_window'
  get 'close_rules_window', to: 'tasks#close_rules_window'
  get 'close_user_position_window', to: 'tasks#close_user_position_window'
  get 'properties', to: 'tasks#properties'
  get 'profile', to: 'tasks#profile'
  get 'help', to: 'tasks#help'
  get 'rsi_activate', to: 'tasks#rsi_activate'
  get 'sync_altama', to: 'tasks#sync_altama'
  get 'bsod', to: 'desktop#bsod'
  get 'close_position_window', to: 'tasks#close_position_window'
  get 'taskbar_button', to: 'tasks#taskbar_button'
  get 'populate_commodity', to: 'codex#populate_commodity'
  get 'destroy_commodity', to: 'codex#destroy_all_commodity'
  get 'destroy_milk_run', to: 'milk_runs#destroy'
  get 'populate_locations', to: 'codex#populate_locations'
  get 'payout_streamchart', to: 'streamchart#payout'
  get 'milkruns_streamchart', to: 'streamchart#milk_run_profits'
  get 'traderuns_streamchart', to: 'streamchart#trade_run_profits'
  get 'star_bitizen_chart', to: 'streamchart#star_bitizen'
  get 'star_bitizen_chart_twitch/:twitch_username', to: 'streamchart#star_bitizen_twitch', as: 'star_bitizen_chart_twitch'
  
  get 'milkrun_profits', to: 'streamchart#milkrun_profits'
  get 'star_bitizen_runs_data', to: 'streamchart#star_bitizen_runs_data'
  get 'star_bitizen_chart_twitch_data/:twitch_id', to: 'streamchart#star_bitizen_twitch_data'
  
  get 'traderun_profits', to: 'streamchart#traderun_profits'

  get 'traderun/:username', to: 'trade_sessions#trade_runs', as: :traderun
  get 'milkrun/:username', to: 'trade_sessions#milk_runs', as: :milkrun

  get 'window_minimize', to: 'windows#minimize'
  get 'window_maximize', to: 'windows#maximize'
  get 'window_close', to: 'windows#close'

  get 'commodities_by_location', to: 'commodities#commodities_by_location'
  post 'deactivate_commodities', to: 'commodities#deactivate_commodities'

  get 'vote', to: 'guildstones#vote'
  get 'unvote', to: 'guildstones#unvote'
  get 'accept_nomination', to: 'position_nominations#accept'
  get 'reject_nomination', to: 'position_nominations#reject'
  
  # User stuff
  get 'display_preferences', to: 'desktop#display_preferences'
  get '/twitch/verify', to: 'users#twitch_verify'
  get '/twitch/redirect', to: 'users#twitch_redirect'
  post 'api_discord_users', to: 'users#discord_populate', as: :discord_populate
  post 'authenticate', to: 'users#auth', as: :auth
  post 'verify', to: 'users#verify', as: :verify
  post 'hangardump', to: 'hangardumps#create', as: :hangardump
  post 'activate', to: 'users#activate', as: :activate
  get 'user_status', to: 'users#user_status', as: :user_status
  #End User

# ASL portion
get 'state_asl_message', to: 'asl#state_asl_message'
get 'asl_add_user', to: 'asl#asl_add_user'
get 'asl_add_contact', to: 'asl#asl_add_contact'
get 'state_modals', to: 'tasks#state_modals'
get 'next_message', to: 'asl#state_asl_message_next'
get 'prev_message', to: 'asl#state_asl_message_prev'
get 'new_asl_message', to: 'asl#state_asl_message_new'

app/controllers/conquest_controller.rb
class ConquestController < ApplicationController
 # before_action :set_rfa, only: %i[ show edit update destroy ]

  # GET /rfas or /rfas.json
  def index
    @events = Event.where(event_type:1)
    @event = Event.new
  end

  # GET /rfas/1 or /rfas/1.json
  def show
    @event = Event.find_by_id(params[:id]) 
    @control_points = ControlPoint.where(event_id: @event.id)
    @control_point = ControlPoint.new    
    @teams = Team.all.order(team_name: :asc)
    @team = Team.new
    @event_records = EventRecord.where(event_id: @event.id).order(start_time: :desc)
    @event_record = EventRecord.new
  end

  def overlay
    @event = Event.find_by_id(params[:id]) 
    @control_points = ControlPoint.where(event_id: @event.id)
  end

  # GET /rfas/new
  def new
    @event = Event.new
  end

  def staff_code
    
@event = Event.find_by(staff_code: params[:staff_code].downcase)
if @event
redirect_to staff_edit_conquest_path(@event)
else
  redirect_to staff_conquest_path
end
  end

  def staff_edit
    @teams = Team.all.order(team_name: :asc)
@event = Event.find_by_id( params[:format])
@control_points = ControlPoint.where(event_id: @event.id)
@event_record = EventRecord.new
  end

  # GET /rfas/1/edit
  def edit
  end


  def staff
    @event = Event.first
  end

  # POST /rfas or /rfas.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rfas/1 or /rfas/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rfas/1 or /rfas/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to rfas_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :rsi_username, :status_id, 
      :location_id, :ship_id, :priority_id, :total_fuel, :total_price, :total_cost, 
      :aec_rewards, :user_assigned_id)      
    end
end

app/views/conquest/_conquest-simple-form.html.erb
<%= form_with(model: event) do |form| %>
  
    <div class="input-row">
      <%= form.text_field :title, placeholder: 'Title'  %>
    </div>
  
    <div class="input-row">
      <%= form.number_field :capture_limit, placeholder: 'Capture limit (mins)' %>
    </div>
  
    <div class="input-row">
      <%= form.label :start_date, style: "display: block" %>
      <%= form.datetime_field :start_date %>
    </div>
  
  
    <%= form.hidden_field :event_type, :value => event_type %>
  
    <div class="submit-row">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/conquest/_conquest-team-form.erb
<%= form_with(model: team) do |form| %>

  
    <div class="input-row">

      <%= form.text_field :team_name, placeholder: 'Team name' %>
    </div>

    <%= form.hidden_field :event_id, :value => event.id %>
  
    <div class="submit-row">
      <%= form.submit "new", class: 'btn' %>
    </div>
  <% end %>
  

app/views/conquest/_conquest-team-form.html.erb
<%= form_with(model: team) do |form| %>

  
    <div class="input-row">

      <%= form.text_field :team_name, placeholder: 'Team name' %>
    </div>


    <%= form.color_field :team_color %>


    <%= form.hidden_field :event_id, :value => event.id %>
  
    <div class="submit-row">
      <%= form.submit "new", class: 'btn' %>
    </div>
  <% end %>
  

app/views/conquest/_control-points-form.html.erb
<%= form_with(model: control_point) do |form| %>

  
    <div class="input-row">
      
      <%= form.text_field :title, placeholder: 'Title' %>
    </div>

    <%= form.hidden_field :event_id, :value => event.id %>
  
    <div class="submit-row">
      <%= form.submit class: 'btn' %>
    </div>
  <% end %>
  

app/views/conquest/index.html.erb
<%= render '/desktop/window-frame', app1: 'ConQuest' %>

<div class="conquest-window">
<h1>ConQuest</h1>

<% unless @events.present? %>


<div class="popup" id="new_event_form">
<h2>Create new event</h2>
<span class="hr">*******************</span>
<%= render "/events/form", event: @event, event_type: 1 %>
</div>

<% else %>

<div data-controller="conquest"  class="popup" id="select_event">
    <h2>List of events</h2>
    <span class="hr">*******************</span>
    <div class="event-list">
        <% @events.each do |event| %>
            <%= link_to conquest_event_path(:id => event.id), class: 'event-row' do %>
            * <%= event.title %> 
            <% end %>
        <% end %>
    </div>
    <span data-action="click->conquest#expand" class="new-event">Create New Event</span>
    <div data-conquest-target="newevent" class="new-event-row">
    <%= render "conquest-simple-form", event: @event, event_type: 1 %>
    </div>
</div>

<% end %>

</div>

<%= render '/desktop/taskbar', app1: 'ConQuest' %>

app/views/conquest/overlay.html.erb
<style>
#conquest{
    background-color:transparent;
}

</style>

<script>
  setTimeout("location.reload();",10000);
</script>

<div class="conquest-overlay" >

<% @control_points.each do | control_point | %>
<div data-controller="conquestoverlay" data-id="<%=control_point.id %>" data-initialprogress="<%= control_point.percent_captured(@event.capture_limit_seconds) %>" class="overlay-chart <%= control_point.iscaptured? %>">
<h4>
Control Point:<br/> <%= control_point.title %>
</h4>
<% if control_point.conquesting %>

	<div class="progress-ring">
	<progress-ring data-conquestoverlay-target="progressring" team-color="<%= control_point.team_color || control_point.team_record_color %>" stroke="8" radius="60" progress="<%= control_point.percent_captured(@event.capture_limit_seconds) %>" ></progress-ring>
	</div>
	<% elsif control_point.iscaptured? %>
	<div class="completed-ring">
	<svg height="120" width="120">
	<circle fill="<%= control_point.team_color || control_point.team_record_color %>" stroke-dasharray="276.46015351590177 276.46015351590177" style="stroke-dashoffset: 0;" stroke-width="8" r="44" cx="60" cy="60"></circle>
	</svg>
	</div>
	
	<% else %>
	<div class="waiting-ring">
	<svg height="120" width="120">
	<circle stroke="grey" stroke-dasharray="276.46015351590177 276.46015351590177" style="stroke-dashoffset: 0;" stroke-width="8" fill="transparent" r="44" cx="60" cy="60"></circle>
	</svg>
	</div>
	<% end %>
	
	<% if  control_point.iscaptured? %>
	<div style="text-align:center;" class="captured-by">Captured by:<br/> <%= control_point.capture_team %></div>
	<% else %>
	<div style="text-align:center;" data-conquestoverlay-target="countdown"  data-starttime="<%= control_point.last_record_time %>" data-capture-limit="<%= @event.capture_limit_seconds || 0 %>"  class="overlay-timers">00:00</div>
	<% end %>
</div>



<% end %>


</div>

app/views/conquest/show.html.erb
<%= render '/desktop/window-frame', app1: 'ConQuest' %>

<div class="conquest-window">
    <div class="conquest-header">
    <div class="logo">    
    <h1>ConQuest</h1>
    </div>
    <div class="overlay-buttons">
    <%= link_to 'Overlay #1', conquest_overlay_path(id: @event.id), class:'btn',  target: '_blank' %>
    </div>
    <div class="staff-code">
    staff code: <%= @event.staff_code %>
    </div>
    <div class="home-button">
    <%= link_to 'MENU', conquest_path, class:'btn' %>
    </div>
    </div>
    <div class="conquest-body">
        <div class="conquest-team column">
            <h2>Teams</h2>
            <div class="create-control-point">
            <%= render "conquest-team-form", team: @team, event: @event %>
        </div>
        
    <div class="control-point-list">
        <% @teams.each do | team | %>
        <%= turbo_frame_tag dom_id(team) do %>
            <div class="event-team">

                <div class="team-column">
                    <div style="color:<%= team.team_color%>" class="team-name">
                    <%= team.team_name %>
                    </div>
                    <div class="team-score">
                    SCORE:<%= team.conquest_duration(@event)%>
                    </div>
                </div>
                <div class="team-column">
                    <%= button_to "DEL", team, class:'btn', style:"color: #{team.team_color}", method: :delete  %>
                </div>
            </div>
        <% end %>
        <% end %>
    </div>

        </div>

        <div class="conquest-controlpoints column">
                <h2>ControlPoints</h2>
                <div class="create-control-point">
                    <%= render "control-points-form", control_point: @control_point, event: @event %>
                </div>
                
            <div class="control-point-list">
                <% @control_points.each do | control_point | %>

                    <div style="background-color: <%= control_point.team_color %>" class="control-point <%= control_point.iscaptured? %>" data-controller="conquesttimer">
                    <h4><%= control_point.title %></h4>
                    <% if control_point.last_record_time %>

                    <div class="timer" data-starttime="<%= control_point.last_record_time %>" data-capture-limit="<%= @event.capture_limit_seconds || 0 %>"  data-conquesttimer-target="timer" ></div>
                    <% end %>
                    <div class="team-container">
                    <ul>
                    <% @teams.each do | team | %>
                        <li data-controller="conquest" class="<%= team.active_control_point(control_point) %> ">
                        <%= form_with(model: control_point, data:{ 'conquesttimer-target' => 'form'}) do |form| %>
                            <%= form.hidden_field :capture_team_id, :value => team.id %>
                            <% end %>
                            
                        <%= form_with(model: @event_record) do |form| %>
                            
                            <%= form.submit team.team_name, data:{ 'action' => 'click->conquest_timer#start'}, class: 'btn' %> 
                            <%= form.hidden_field :team_id, :value => team.id %> <%= form.hidden_field :event_id, :value => @event.id %> <%= form.hidden_field :control_point_id, :value => control_point.id %> <% end %></li>
                       
                    <% end %>
                    </ul>
                </div>
                <div class="control-point-timer">
                <% if control_point.iscaptured? %>
                    <%= link_to 'REMOVE', stop_conquest_path(id: control_point) %>
                    <% else %>
                    <%= link_to 'CAPTURE', capture_conquest_path(id: control_point) %>
                    <% end %>
                    <%= link_to 'CLEAR', clear_conquest_records_path(id: control_point) %>
                    
                    </div>
                    </div>

                <% end %>
            </div>
        </div>

        <div class="conquest-records column">
            <h2>Records</h2>
            <div class="control-point-list">
                <% @event_records.each do | event_record | %>
                <div style="border: 2px solid <%= event_record.team.team_color %>" class="event-record-card">
                Team: <%= event_record.team.team_name %> 
                Start_Time: <%= event_record.start_time.utc.strftime('%H:%M:%S') %>
                <% if event_record.end_time %>
                End_Time: <%= event_record.end_time.utc.strftime('%H:%M:%S') %>
                <% end %>
                <% if event_record.duration %>
                Duration: <%= event_record.duration %>
                <% end %>
                CTRL_PT: <%= event_record.control_point %> 
                </div>
                <% end %>
            </div>


        </div>

    </div>
</div>
<%= render '/desktop/taskbar', app1: 'ConQuest' %>

app/views/conquest/staff.html.erb
<%= render '/desktop/window-frame', app1: 'ConQuest' %>

<div class="conquest-window">
    <div class="conquest-header">
        <div class="logo">    
            <h1>ConQuest</h1>
        </div>
    </div>
    <div class="staff">
        <%= form_with url: staff_code_path do |f|  %>
            <%= f.text_field :staff_code  %>
            <%= f.submit :ENTER  %>
        <% end %>
    </div>

</div>

app/views/conquest/staff_edit.html.erb
<%= render '/desktop/window-frame', app1: 'ConQuest' %>

<div class="conquest-window">
    <div class="conquest-header">
        <div class="logo">    
            <h1>ConQuest Staff Editor</h1>
        </div>
    </div>
    <div class="staff">


<div class="conquest-window conquest-body">

        <div class="conquest-controlpoints column">
                <h2>ControlPoints</h2>

                
            <div class="control-point-list">
                <% @control_points.each do | control_point | %>

                    <div style="background-color: <%= control_point.team_color %>" class="control-point <%= control_point.iscaptured? %>" data-controller="conquesttimer">
                    <h4><%= control_point.title %></h4>
                    <% if control_point.last_record_time %>

                    <div class="timer" data-starttime="<%= control_point.last_record_time %>" data-capture-limit="<%= @event.capture_limit_seconds || 0 %>"  data-conquesttimer-target="timer" ></div>
                    <% end %>
                    <div class="staff team-container">
                    <ul>
                    <% @teams.each do | team | %>
                        <li data-controller="conquest" class="<%= team.active_control_point(control_point) %> ">
                        <%= form_with(model: control_point, data:{ 'conquesttimer-target' => 'form'}) do |form| %>
                            <%= form.hidden_field :capture_team_id, :value => team.id %>
                            <% end %>
                            
                        <%= form_with(model: @event_record) do |form| %>
                            
                            <%= form.submit team.team_name, data:{ 'action' => 'click->conquest_timer#start'}, class: 'btn' %> 
                            <%= form.hidden_field :team_id, :value => team.id %> <%= form.hidden_field :event_id, :value => @event.id %> <%= form.hidden_field :control_point_id, :value => control_point.id %> <% end %></li>
                       
                    <% end %>
                    </ul>
                </div>
                <div class="control-point-timer">
                <% if control_point.iscaptured? %>
                    <%= link_to 'REMOVE', stop_conquest_path(id: control_point) %>
                    <% else %>
                    <%= link_to 'CAPTURE', capture_conquest_path(id: control_point) %>
                    <% end %>
                    <%= link_to 'CLEAR', clear_conquest_records_path(id: control_point) %>
                    
                    </div>
                    </div>

                <% end %>
            </div>
        </div>

    </div>
</div>

    </div>

</div>