config/routes.rb
Rails.application.routes.draw do
  jsonapi_resources :rfaapi
  jsonapi_resources :location
  jsonapi_resources :commodity
  jsonapi_resources :online

  resources :non_confidences
  resources :rule_proposals
  resources :categories

  resources :trade_runs do
    patch :update_traderun_location, on: :member
  end
  resources :milk_runs
  resources :bots do
  resources :giveaways, only: %i[new show create edit update destroy]
    patch 'toggle_online', on: :member
  end
  resources :trade_sessions
  
  mount ActionCable.server => "/cable"

  constraints subdomain: "sos" do
    get "/" => "web#roadside_assistance"
   end

  resources :articles
  resources :departments do
    resources :users, only: :index
  end

  namespace :api do
    namespace :v1 do
      jsonapi_resources :userships
      resources :star_bitizen_races, only: [:index]
    end
  end




  resources :users, only: [:edit, :update]

  resources :positions
  resources :rules
  resources :user_position_histories
  resources :user_positions
  #resources :votes
  resources :position_nominations
  resources :org_roles
  resources :guildstones
  resources :locations
  resources :tasks
  resources :userships
  resources :manufacturers
  resources :event_records
  resources :event_teams
  resources :event_users
  resources :event_series
  resources :teams
  resources :events
  resources :ships
  resources :rfas
  resources :reviews
  resources :rfa_products
  resources :commodities
  resources :rewards
  resources :control_points
  resources :badges
  resources :user_badges
  resources :categories
  resources :rule_proposals
  resources :messages


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: 'users/sessions' }
  # Defines the root path route ("/")
   
  root 'welcome#index', :constraints => { :subdomain => "ctd" }
  get 'desktop', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'bootup', to: 'desktop#bootup', :constraints => { :subdomain => "ctd" }
  # get 'rfas', to: 'rfas#index'
  get 'conquest', to: 'conquest#index', :constraints => { :subdomain => "ctd" }

  resource :conquest do
    get 'staff', to: 'conquest#staff', :constraints => { :subdomain => "ctd" }
    get 'staff_edit', to: 'conquest#staff_edit', :constraints => { :subdomain => "ctd" }
  end

  post 'staff_code', to: 'conquest#staff_code',  as: :staff_code, :constraints => { :subdomain => "ctd" }
  get 'ship_components', to: 'ship_components#index'
  get 'conquest_event', to: 'conquest#show', :constraints => { :subdomain => "ctd" }
  get 'clear_conquest_records', to: 'event_records#clear_control_points'
  get 'stop_conquest', to: 'control_points#stop_conquest', :constraints => { :subdomain => "ctd" }
  get 'capture_conquest', to: 'control_points#capture_conquest', :constraints => { :subdomain => "ctd" }
  get 'conquest_overlay', to: 'conquest#overlay'
  get 'cargo_manifest', to: 'cargo_manifest#welcome', :constraints => { :subdomain => "ctd" }
  get 'website_manager', to: 'website_manager#welcome'
  get 'my_hangar', to: 'my_hangar#index'
  get 'start_my_hangar', to: 'tasks#start_my_hangar'
  get 'my_hangar_import', to: 'hangardump#index'
  get 'my_hangar_add', to: 'my_hangar#add'
  get 'my_hangar_manage', to: 'my_hangar#manage'
  get 'my_hangar_all_fleet', to: 'my_hangar#all_fleet'
  get 'my_hangar_all_fleet_remove', to: 'my_hangar#all_fleet_remove'
  get 'my_hangar_destroy', to: 'my_hangar#clear_ships'
  get 'my_badges', to: 'badges#my_badges'
  get 'clear_memos', to: 'tasks#clear_memos'
  get 'my_hangar_view', to: 'my_hangar#view'
  get 'fleet_view', to: 'my_hangar#fleet_view'
  get 'users', to: 'desktop#users'
  get 'all_users', to: 'users#all_users'
  get 'roadside_assistance', to: 'web#roadside_assistance'
  get 'current_review', to: 'web#current_review'
  get 'rfa_location', to: 'web#show'
  get 'ship_view', to: 'desktop#ship_view_switch'
  get 'select_ship', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'apply_role', to: 'guildstones#apply_role'
  #get 'vote', to: 'guildstones#vote'
  get 'killall', to:'tasks#killall'
  get 'start_guildstone', to:'tasks#start_guildstone'
  get 'guildstone_start_asl', to: 'guildstones#guildstone_start_asl'
  get 'guildstone_org_chart', to: 'guildstones#open_org_chart'
  get 'guildstone_all_applications', to: 'guildstones#all_applications'
  get 'guildstone_all_nominations', to: 'guildstones#all_nominations'
  
  get 'start_rfa_manager', to: 'tasks#start_rfa_manager'
  get 'rfas_online', to: 'rfas#online'
  get 'start_shell', to: 'tasks#start_shell'
  get 'start_codex', to: 'tasks#start_codex'
  post 'vim_command', to: 'vim#vim_command'

  get 'start_bot_manager', to: 'tasks#start_bot_manager'
  get 'start_asl', to: 'tasks#start_asl'
  get 'codex_timeline', to: 'codex#timeline'
  get 'codex_article', to: 'codex#article'
  get 'codex_data_processor', to: 'codex#codex_data_processor'
  get 'codex_create_article', to: 'codex#create_article'
  get 'codex_edit_article', to: 'codex#edit_article'
  get 'codex_show_article', to: 'codex#show_article'
  get 'codex_back_article', to: 'codex#back_article'
  get 'codex_find_article', to: 'codex#find_article'
  get 'codex_dossier', to: 'codex#create_dossier'
  get 'verify_username', to: 'codex#verify_username'
  get '/invite/:id', to: 'codex#invite', as: 'invite'
  post '/event_join', to: 'codex#event_join', as: 'event_join'



  get 'close_find_window', to: 'codex#close_find_window'
  get 'close_codex_window', to: 'codex#close_codex_window'
  get 'join_event', to: 'event_users#join'
  get 'leave_event', to: 'event_users#leave'
  get 'open_event', to: 'events#open_event'
  get 'command', to: 'shell#command_entry'
  get 'acu_command', to: 'shell#acu_command_entry'
  get 'traderun_command', to: 'shell#traderun_command_entry'
  get 'start_location_manager', to:'tasks#start_location_manager'
  get 'start_ship_manager', to:'tasks#start_ship_manager'
  get 'rsi_user_list', to: 'desktop#rsi_user_list'
  get 'all_user_list', to: 'tasks#state_all_users'
  get 'root_user_list', to: 'tasks#state_root_users'
  get 'twitch_user_list', to: 'tasks#state_twitch_users'
  get 'discord_user_list', to: 'tasks#state_discord_users'
  get 'state_positions', to: 'tasks#state_positions'
  get 'all_state_positions', to: 'tasks#all_state_positions'
  get 'state_user_positions', to: 'tasks#state_user_positions'
  get 'initiate_ship_modal', to: 'tasks#state_ship_modal'
  get 'state_rules', to: 'tasks#state_rules'
  get 'filter_state', to: 'tasks#filter_state'
  get 'state_location_wizard', to: 'tasks#state_location_wizard'

  get 'state_location_edit', to: 'tasks#state_location_edit'
  get 'state_location_subitem', to:'tasks#state_location_subitem'
  get 'state_location_mainitem', to:'tasks#state_location_mainitem'
  get 'close_state_window', to: 'tasks#close_state_window'
  get 'close_last_window', to: 'tasks#close_last_window'
  get 'close_rules_window', to: 'tasks#close_rules_window'
  get 'close_user_position_window', to: 'tasks#close_user_position_window'
  get 'properties', to: 'tasks#properties'
  get 'profile', to: 'tasks#profile'
  get 'help', to: 'tasks#help'
  get 'rsi_activate', to: 'tasks#rsi_activate'
  get 'sync_altama', to: 'tasks#sync_altama'
  get 'bsod', to: 'desktop#bsod'
  get 'close_position_window', to: 'tasks#close_position_window'
  get 'taskbar_button', to: 'tasks#taskbar_button'
  get 'populate_commodity', to: 'codex#populate_commodity'
  get 'destroy_commodity', to: 'codex#destroy_all_commodity'
  get 'destroy_milk_run', to: 'milk_runs#destroy'
  get 'populate_locations', to: 'codex#populate_locations'
  get 'payout_streamchart', to: 'streamchart#payout'
  get 'milkruns_streamchart', to: 'streamchart#milk_run_profits'
  get 'traderuns_streamchart', to: 'streamchart#trade_run_profits'
  get 'star_bitizen_chart', to: 'streamchart#star_bitizen'
  get 'star_bitizen_chart_twitch/:twitch_username', to: 'streamchart#star_bitizen_twitch', as: 'star_bitizen_chart_twitch'
  
  get 'milkrun_profits', to: 'streamchart#milkrun_profits'
  get 'star_bitizen_runs_data', to: 'streamchart#star_bitizen_runs_data'
  get 'star_bitizen_chart_twitch_data/:twitch_id', to: 'streamchart#star_bitizen_twitch_data'
  
  get 'traderun_profits', to: 'streamchart#traderun_profits'

  get 'traderun/:username', to: 'trade_sessions#trade_runs', as: :traderun
  get 'milkrun/:username', to: 'trade_sessions#milk_runs', as: :milkrun

  get 'window_minimize', to: 'windows#minimize'
  get 'window_maximize', to: 'windows#maximize'
  get 'window_close', to: 'windows#close'

  get 'commodities_by_location', to: 'commodities#commodities_by_location'
  post 'deactivate_commodities', to: 'commodities#deactivate_commodities'

  get 'vote', to: 'guildstones#vote'
  get 'unvote', to: 'guildstones#unvote'
  get 'accept_nomination', to: 'position_nominations#accept'
  get 'reject_nomination', to: 'position_nominations#reject'
  
  # User stuff
  get 'display_preferences', to: 'desktop#display_preferences'
  get '/twitch/verify', to: 'users#twitch_verify'
  get '/twitch/redirect', to: 'users#twitch_redirect'
  post 'api_discord_users', to: 'users#discord_populate', as: :discord_populate
  post 'authenticate', to: 'users#auth', as: :auth
  post 'verify', to: 'users#verify', as: :verify
  post 'hangardump', to: 'hangardumps#create', as: :hangardump
  post 'activate', to: 'users#activate', as: :activate
  get 'user_status', to: 'users#user_status', as: :user_status
  #End User

# ASL portion
get 'state_asl_message', to: 'asl#state_asl_message'
get 'asl_add_user', to: 'asl#asl_add_user'
get 'asl_add_contact', to: 'asl#asl_add_contact'
get 'state_modals', to: 'tasks#state_modals'
get 'next_message', to: 'asl#state_asl_message_next'
get 'prev_message', to: 'asl#state_asl_message_prev'
get 'new_asl_message', to: 'asl#state_asl_message_new'

app/models/usership.rb
class Usership < ApplicationRecord
    belongs_to :user
   # belongs_to :ship, foreign_key: 'ship_name', primary_key: 'model'
    belongs_to :ship
    has_one_attached :attachment
    include ActiveModel::Serializers::JSON
    after_update_commit {broadcast_replace_to 'usership_details', partial: '/my_hangar/usership_details', locals: { usership_details: self }}
    has_many :usership_components, dependent: :destroy

    def fid_processor(id1, id2)
        
        
        ship = ''
        code = self.ship.code
        fid = code + id1.to_s.upcase + '-' + id2.to_s.upcase
        fid
    end

    def generate_fid(digits)
        SecureRandom.base64.delete('/+=')[0, digits]
    end



    def filter


        filter_type = "|#{params[:filter_type]}"
        filter_option = "|#{params[:filter_option]}"
        @myships = Usership.where(user_id: current_user.id)
        if params[:filter_type] == 'manufacturer'
        @myships_filtered = []
        @myships.each_with_index do | usership, i |
        if usership.ship.manufacturer.name.downcase.include? params[:filter_option]
        @myships_filtered << usership
        end
        end
        # @filtered_ships = @myships.joins(:manufacturers).where(:manufacturers => {:name => "Origin Jumpworks (ORIG)"})
        #@myships.joins(:ship).where('manufacturers.name = ?', "Origin Jumpworks (ORIG)")
        end

    end

end

app/controllers/api/v1/userships_controller.rb
module Api
  module V1
    class UsershipsController < JSONAPI::ResourceController
      # your controller actions here
    end
  end
end

app/controllers/userships_controller.rb
class UsershipsController < ApplicationController
  before_action :set_usership, only: %i[ show edit update destroy ]
  include ActionView::Helpers::UrlHelper

  before_action :redirect_cancel, only: [:create, :update]


  # GET /userships or /userships.json
  def index
    @userships = Usership.all
  end

  # GET /userships/1 or /userships/1.json
  def show
  end

  # GET /userships/new
  def new
    @usership = Usership.new
  end

  # GET /userships/1/edit
  def edit
  end

  # POST /userships or /userships.json
  def create    
    @usership = Usership.new(usership_params)    
    @usership.update(user_id:current_user.id, ship_name: usership_params[:model])

    respond_to do |format|
     # if @usership.save
        #flash[:notice] = "Post has been saved successfully."
      if @usership.save 
        format.html { redirect_to request.referrer, notice: "Usership was successfully created." }
        format.json { render :show, status: :created, location: @usership }
      else
        format.html { redirect_to request.referrer, notice: "Error" }
        format.json { render json: @usership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userships/1 or /userships/1.json
  def update
    
    usership = Usership.find_by_id(params[:id])
  #  usership_params[:fid] = usership.fid_processor(usership_params[:fid_01],usership_params[:fid_02])
  #param_1 = usership_params[:fid_01]
  
  param_1 = params[:usership][:fid_01].to_s
  param_2 =params[:usership][:fid_02].to_s
  
   
    
    respond_to do |format|
      if usership_params[:primary] == "1"
        primary_userships = Usership.find_by(user_id: current_user.id, primary: 1)
        primary_userships.update(primary:0)
      end
      if usership_params[:show_information] == "0"
        @usership.update(usership_params.except(:fid_01, :fid_02).merge(show_information:nil, fid: nil))
        return
      end

      if @usership.update(usership_params.except(:fid_01, :fid_02).merge(fid: usership.fid_processor(param_1,param_2)))
        
      #  format.turbo_stream { render turbo_stream: turbo_stream.update(@usership) }
      #format.turbo_stream do
      #  render turbo_stream: turbo_stream.append(:userships, partial: "userships/usership_details",
      #    locals: { usership: @usership })
      #end

    # format.turbo_stream
      #  format.html { redirect_to @usership, notice: "Usership was successfully updated." }
      #  format.json { render :show, status: :ok, location: @usership }
     # render partial: 'usership'
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userships/1 or /userships/1.json
  def destroy
    
    @usership.destroy
    respond_to do |format|
      format.html { redirect_to my_hangar_manage_path, notice: "Usership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
  def redirect_cancel
    redirect_to request.referrer if params[:cancel]
  end
    
    def set_usership
      @usership = Usership.find(params[:id])
    end

    
    def usership_params     
      params.require(:usership).permit(:user_id, :model, :ship_serial, :pledge_id, :show_information,
      :pledge_name, :pledge_date, :lti, :warbond, :year_purchased, :description, :paint, :primary, :fid, :fid_01,:fid_02)
    end
end

app/helpers/userships_helper.rb
module UsershipsHelper
end

app/views/userships/_edit_ships.html.erb
<%= turbo_frame_tag usership do %>
<%= form_with(model: usership) do |form| %>
  <% if usership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usership.errors.count, "error") %> prohibited this usership from being saved:</h2>
      <ul>
        <% usership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ship_name %>
    <%= form.text_field :ship_name %>
  </div>

  <div>
    <%= form.label :year %>
    <%= form.number_field :year_purchased %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="input-group">
    <div class="primary-ship-container">
      <%= form.label :primary %>
      <%= form.check_box :primary %>
    </div>

    <div class="altama-fleet-actions">
    <div>
      <%= form.label :altama_fleet %>
      <%= form.check_box :show_information, 'data-action': "click->hangarEditor#clickedFID" %>
    </div>
      <div class="fleet-id-field <% unless usership.show_information %>hide<%end%>" data-hangarEditor-target="fid">
      <span class="fleet-id-label">FleetID:</span>
      <% if usership.fid %>
          <% @fid_01 = usership.fid.split('-').first[-4..-1] %>
          <% @fid_02 = usership.fid.split('-').last[-10..-1] %>
        <% else %>
          <% @fid_01 = usership.generate_fid(4) %>
          <% @fid_02 = usership.generate_fid(10) %>
      <% end %>
      <%= form.text_field :fid_01, maxlength: 4, id:'field01', :value => "#{@fid_01}" %>-<%= form.text_field :fid_02, maxlength: 10, :value => "#{@fid_02}" %>
    </div>

    </div>

  </div>

  <div>
    <%= form.submit 'Update' %>
    <% if usership.source == "imported" %>
    <%= link_to "Remove ship", usership_path(usership), class: 'btn red', 'data-turbo-method': :delete  %>
    <% end %>
  </div>
<% end %>

<% end %>

app/views/userships/_form.html.erb
<%= form_with(model: usership) do |form| %>
  <% if usership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usership.errors.count, "error") %> prohibited this usership from being saved:</h2>

      <ul>
        <% usership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ship_name, style: "display: block" %>
    <%= form.text_field :ship_name %>
  </div>

  <div>
    <%= form.label :year_purchased, style: "display: block" %>
    <%= form.number_field :year_purchased %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :ship_id, style: "display: block" %>
    <%= form.number_field :ship_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  
  <div>
    <%= form.label :paint, style: "display: block" %>
    <%= form.text_field :paint %>
  </div>
  <div>
  <%= form.label :primary, style: "display: block" %>
  <%= form.check_box :primary %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/userships/_usership-form.html.erb
 <%= form_with(model: usership, :html => {:id => 'userships_form', :style => 'display:none;' }) do |forma| %>
  <% if usership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usership.errors.count, "error") %> prohibited this usership from being saved:</h2>

      <ul>
        <% usership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field flex-row" style="margin-top:5px; margin-bottom:10px;">
  <%= forma.select :model, options_for_select(@ships.collect{ |u| [u.model, u.model] } ), {:include_blank => 'Select New Ship', :required=>"true"},  {data:{ action: 'change->web#shipSelect'}} %>
  <%= forma.label "Primary?" %>
  <%= forma.check_box :primary %>
    </div>
<div class="field">
  <%= forma.submit "Select Ship", class: 'cta', id: 'usership_submit', disabled: 'true'  %>

<%= button_tag t('buttons.cancel'), type: "submit", name: "cancel", class:'cta red', value: true %>

</div>
<% end %>
  

  

app/views/userships/_usership.html.erb
<div id="<%= dom_id usership %>">
  <p>
    <strong>Ship name:</strong>
    <%= usership.ship_name %>
  </p>

  <p>
    <strong>Year purchased:</strong>
    <%= usership.year_purchased %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= usership.description %>
  </p>

  <p>
    <strong>Ship:</strong>
    <%= usership.ship_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= usership.user_id %>
  </p>

  <p>
    <strong>Paint:</strong>
    <%= usership.paint %>
  </p>

  <p>
    <%= link_to "Show this usership", usership %>
  </p>
</div>

app/views/userships/_usership_details.html.erb
<div id="<%= dom_id usership %>">
<% if usership.show_information %><span class="primary-ship">Fleet ship</span><% end %>
    <% if usership.primary %><span class="primary-ship">Primary ship</span><% end %>
        <h5>Ship name: <%= usership.ship_name || 'unnamed' %></h5>
        
    <% if usership.fid %>
        <h5>Fleet ID:ALT-<%= usership.fid %></h5>
    <% end %>
</div>

app/views/userships/edit.html.erb
<%= turbo_frame_tag @usership do %>
<h1>Editing usership</h1>

<%= render "form", usership: @usership %>

<br>

<div>
  <%= link_to "Show this usership", @usership %> |
  <%= link_to "Back to userships", userships_path %>
</div>



  <%#= link_to 'Cancel', todo_path(@todo) %>
<% end %>

app/views/userships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Userships</h1>

<div id="userships">
  <%= render @userships %>
</div>

<%= link_to "New usership", new_usership_path %>

app/views/userships/new.html.erb
<h1>New usership</h1>

<%= render "form", usership: @usership %>

<br>

<div>
  <%= link_to "Back to userships", userships_path %>
</div>

app/views/userships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usership %>

<div>
  <%= link_to "Edit this usership", edit_usership_path(@usership) %> |
  <%= link_to "Back to userships", userships_path %>

  <%= button_to "Destroy this usership", usership_path(@usership), method: :delete %>
</div>

app/views/userships/update.turbo_stream.erb
<%# not used %>
test