config/routes.rb
Rails.application.routes.draw do
  jsonapi_resources :rfaapi
  jsonapi_resources :location
  jsonapi_resources :commodity
  jsonapi_resources :online

  resources :non_confidences
  resources :rule_proposals
  resources :categories

  resources :trade_runs do
    patch :update_traderun_location, on: :member
  end
  resources :milk_runs
  resources :bots do
  resources :giveaways, only: %i[new show create edit update destroy]
    patch 'toggle_online', on: :member
  end
  resources :trade_sessions
  
  mount ActionCable.server => "/cable"

  constraints subdomain: "sos" do
    get "/" => "web#roadside_assistance"
   end

  resources :articles
  resources :departments do
    resources :users, only: :index
  end

  namespace :api do
    namespace :v1 do
      jsonapi_resources :userships
      resources :star_bitizen_races, only: [:index]
    end
  end




  resources :users, only: [:edit, :update]

  resources :positions
  resources :rules
  resources :user_position_histories
  resources :user_positions
  #resources :votes
  resources :position_nominations
  resources :org_roles
  resources :guildstones
  resources :locations
  resources :tasks
  resources :userships
  resources :manufacturers
  resources :event_records
  resources :event_teams
  resources :event_users
  resources :event_series
  resources :teams
  resources :events
  resources :ships
  resources :rfas
  resources :reviews
  resources :rfa_products
  resources :commodities
  resources :rewards
  resources :control_points
  resources :badges
  resources :user_badges
  resources :categories
  resources :rule_proposals
  resources :messages


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: 'users/sessions' }
  # Defines the root path route ("/")
   
  root 'welcome#index', :constraints => { :subdomain => "ctd" }
  get 'desktop', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'bootup', to: 'desktop#bootup', :constraints => { :subdomain => "ctd" }
  # get 'rfas', to: 'rfas#index'
  get 'conquest', to: 'conquest#index', :constraints => { :subdomain => "ctd" }

  resource :conquest do
    get 'staff', to: 'conquest#staff', :constraints => { :subdomain => "ctd" }
    get 'staff_edit', to: 'conquest#staff_edit', :constraints => { :subdomain => "ctd" }
  end

  post 'staff_code', to: 'conquest#staff_code',  as: :staff_code, :constraints => { :subdomain => "ctd" }
  get 'ship_components', to: 'ship_components#index'
  get 'conquest_event', to: 'conquest#show', :constraints => { :subdomain => "ctd" }
  get 'clear_conquest_records', to: 'event_records#clear_control_points'
  get 'stop_conquest', to: 'control_points#stop_conquest', :constraints => { :subdomain => "ctd" }
  get 'capture_conquest', to: 'control_points#capture_conquest', :constraints => { :subdomain => "ctd" }
  get 'conquest_overlay', to: 'conquest#overlay'
  get 'cargo_manifest', to: 'cargo_manifest#welcome', :constraints => { :subdomain => "ctd" }
  get 'website_manager', to: 'website_manager#welcome'
  get 'my_hangar', to: 'my_hangar#index'
  get 'start_my_hangar', to: 'tasks#start_my_hangar'
  get 'my_hangar_import', to: 'hangardump#index'
  get 'my_hangar_add', to: 'my_hangar#add'
  get 'my_hangar_manage', to: 'my_hangar#manage'
  get 'my_hangar_all_fleet', to: 'my_hangar#all_fleet'
  get 'my_hangar_all_fleet_remove', to: 'my_hangar#all_fleet_remove'
  get 'my_hangar_destroy', to: 'my_hangar#clear_ships'
  get 'my_badges', to: 'badges#my_badges'
  get 'clear_memos', to: 'tasks#clear_memos'
  get 'my_hangar_view', to: 'my_hangar#view'
  get 'fleet_view', to: 'my_hangar#fleet_view'
  get 'users', to: 'desktop#users'
  get 'all_users', to: 'users#all_users'
  get 'roadside_assistance', to: 'web#roadside_assistance'
  get 'current_review', to: 'web#current_review'
  get 'rfa_location', to: 'web#show'
  get 'ship_view', to: 'desktop#ship_view_switch'
  get 'select_ship', to: 'desktop#index', :constraints => { :subdomain => "ctd" }
  get 'apply_role', to: 'guildstones#apply_role'
  #get 'vote', to: 'guildstones#vote'
  get 'killall', to:'tasks#killall'
  get 'start_guildstone', to:'tasks#start_guildstone'
  get 'guildstone_start_asl', to: 'guildstones#guildstone_start_asl'
  get 'guildstone_org_chart', to: 'guildstones#open_org_chart'
  get 'guildstone_all_applications', to: 'guildstones#all_applications'
  get 'guildstone_all_nominations', to: 'guildstones#all_nominations'
  
  get 'start_rfa_manager', to: 'tasks#start_rfa_manager'
  get 'rfas_online', to: 'rfas#online'
  get 'start_shell', to: 'tasks#start_shell'
  get 'start_codex', to: 'tasks#start_codex'
  post 'vim_command', to: 'vim#vim_command'

  get 'start_bot_manager', to: 'tasks#start_bot_manager'
  get 'start_asl', to: 'tasks#start_asl'
  get 'codex_timeline', to: 'codex#timeline'
  get 'codex_article', to: 'codex#article'
  get 'codex_data_processor', to: 'codex#codex_data_processor'
  get 'codex_create_article', to: 'codex#create_article'
  get 'codex_edit_article', to: 'codex#edit_article'
  get 'codex_show_article', to: 'codex#show_article'
  get 'codex_back_article', to: 'codex#back_article'
  get 'codex_find_article', to: 'codex#find_article'
  get 'codex_dossier', to: 'codex#create_dossier'
  get 'verify_username', to: 'codex#verify_username'
  get '/invite/:id', to: 'codex#invite', as: 'invite'
  post '/event_join', to: 'codex#event_join', as: 'event_join'



  get 'close_find_window', to: 'codex#close_find_window'
  get 'close_codex_window', to: 'codex#close_codex_window'
  get 'join_event', to: 'event_users#join'
  get 'leave_event', to: 'event_users#leave'
  get 'open_event', to: 'events#open_event'
  get 'command', to: 'shell#command_entry'
  get 'acu_command', to: 'shell#acu_command_entry'
  get 'traderun_command', to: 'shell#traderun_command_entry'
  get 'start_location_manager', to:'tasks#start_location_manager'
  get 'start_ship_manager', to:'tasks#start_ship_manager'
  get 'rsi_user_list', to: 'desktop#rsi_user_list'
  get 'all_user_list', to: 'tasks#state_all_users'
  get 'root_user_list', to: 'tasks#state_root_users'
  get 'twitch_user_list', to: 'tasks#state_twitch_users'
  get 'discord_user_list', to: 'tasks#state_discord_users'
  get 'state_positions', to: 'tasks#state_positions'
  get 'all_state_positions', to: 'tasks#all_state_positions'
  get 'state_user_positions', to: 'tasks#state_user_positions'
  get 'initiate_ship_modal', to: 'tasks#state_ship_modal'
  get 'state_rules', to: 'tasks#state_rules'
  get 'filter_state', to: 'tasks#filter_state'
  get 'state_location_wizard', to: 'tasks#state_location_wizard'

  get 'state_location_edit', to: 'tasks#state_location_edit'
  get 'state_location_subitem', to:'tasks#state_location_subitem'
  get 'state_location_mainitem', to:'tasks#state_location_mainitem'
  get 'close_state_window', to: 'tasks#close_state_window'
  get 'close_last_window', to: 'tasks#close_last_window'
  get 'close_rules_window', to: 'tasks#close_rules_window'
  get 'close_user_position_window', to: 'tasks#close_user_position_window'
  get 'properties', to: 'tasks#properties'
  get 'profile', to: 'tasks#profile'
  get 'help', to: 'tasks#help'
  get 'rsi_activate', to: 'tasks#rsi_activate'
  get 'sync_altama', to: 'tasks#sync_altama'
  get 'bsod', to: 'desktop#bsod'
  get 'close_position_window', to: 'tasks#close_position_window'
  get 'taskbar_button', to: 'tasks#taskbar_button'
  get 'populate_commodity', to: 'codex#populate_commodity'
  get 'destroy_commodity', to: 'codex#destroy_all_commodity'
  get 'destroy_milk_run', to: 'milk_runs#destroy'
  get 'populate_locations', to: 'codex#populate_locations'
  get 'payout_streamchart', to: 'streamchart#payout'
  get 'milkruns_streamchart', to: 'streamchart#milk_run_profits'
  get 'traderuns_streamchart', to: 'streamchart#trade_run_profits'
  get 'star_bitizen_chart', to: 'streamchart#star_bitizen'
  get 'star_bitizen_chart_twitch/:twitch_username', to: 'streamchart#star_bitizen_twitch', as: 'star_bitizen_chart_twitch'
  
  get 'milkrun_profits', to: 'streamchart#milkrun_profits'
  get 'star_bitizen_runs_data', to: 'streamchart#star_bitizen_runs_data'
  get 'star_bitizen_chart_twitch_data/:twitch_id', to: 'streamchart#star_bitizen_twitch_data'
  
  get 'traderun_profits', to: 'streamchart#traderun_profits'

  get 'traderun/:username', to: 'trade_sessions#trade_runs', as: :traderun
  get 'milkrun/:username', to: 'trade_sessions#milk_runs', as: :milkrun

  get 'window_minimize', to: 'windows#minimize'
  get 'window_maximize', to: 'windows#maximize'
  get 'window_close', to: 'windows#close'

  get 'commodities_by_location', to: 'commodities#commodities_by_location'
  post 'deactivate_commodities', to: 'commodities#deactivate_commodities'

  get 'vote', to: 'guildstones#vote'
  get 'unvote', to: 'guildstones#unvote'
  get 'accept_nomination', to: 'position_nominations#accept'
  get 'reject_nomination', to: 'position_nominations#reject'
  
  # User stuff
  get 'display_preferences', to: 'desktop#display_preferences'
  get '/twitch/verify', to: 'users#twitch_verify'
  get '/twitch/redirect', to: 'users#twitch_redirect'
  post 'api_discord_users', to: 'users#discord_populate', as: :discord_populate
  post 'authenticate', to: 'users#auth', as: :auth
  post 'verify', to: 'users#verify', as: :verify
  post 'hangardump', to: 'hangardumps#create', as: :hangardump
  post 'activate', to: 'users#activate', as: :activate
  get 'user_status', to: 'users#user_status', as: :user_status
  #End User

# ASL portion
get 'state_asl_message', to: 'asl#state_asl_message'
get 'asl_add_user', to: 'asl#asl_add_user'
get 'asl_add_contact', to: 'asl#asl_add_contact'
get 'state_modals', to: 'tasks#state_modals'
get 'next_message', to: 'asl#state_asl_message_next'
get 'prev_message', to: 'asl#state_asl_message_prev'
get 'new_asl_message', to: 'asl#state_asl_message_new'

app/models/guildstone.rb
class Guildstone < ApplicationRecord
  has_many :departments
end

app/helpers/guildstones_helper.rb
module GuildstonesHelper
end

app/views/guildstones/_form.html.erb
<%= form_with(model: guildstone) do |form| %>
  <% if guildstone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guildstone.errors.count, "error") %> prohibited this guildstone from being saved:</h2>

      <ul>
        <% guildstone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :charter, style: "display: block" %>
    <%= form.text_field :charter %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guildstones/_guildstone.html.erb
<div id="<%= dom_id guildstone %>">
  <p>
    <strong>Charter:</strong>
    <%= guildstone.charter %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= guildstone.title %>
  </p>

  <p>
    <%= link_to "Show this guildstone", guildstone %>
  </p>
</div>

app/views/guildstones/_modal-all_applications.html.erb
<div draggable="true" class="guildstone-modal org_chart" 
<% if i > 0 %>
style="transform: translate(
    calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
    z-index: <%= i %>"
<%end%> >
    <div class="section-window-header">    
    All Applications
        <%= link_to "", close_state_window_path(window: 'allApplications-Guildstone', task: @current_task.id), class:'close-btn windowed' %>
    </div>
    <div class="modal-container general">
        <div class="position-header">
        All applications available
        </div>
        <div class="general-view">
<div class="general-header">
    <div>TITLE</div>
    <div>DESCRIPTION</div>
    <div>DEPARTMENT</div>
    <div></div>
</div>
<% if Position.all.count > 0 %>
        <% Position.all.each do |position|  %>
            <div class="general-rows">
            <span><%= position.title %></span>
            <p><%= position.description %></p>
            <p><%= position.department.title %></p>


            <% unless position.user_position || position.nomination(current_user.id)  %>
            <%= form_with(model: PositionNomination) do |form| %>
                <%= form.hidden_field :position_id, :value => position.id %>
                <%= form.hidden_field :nominee_id, :value => current_user.id%>

                <br/>
                <%= form.label :resume, "Resume: " %>
                <br/>
                <%= form.text_area :resume %>
                <br/>
                <%= form.submit 'Apply' %>
            <% end %>
            <% else %>
            <p>Application Submitted!</p>
        <% end %>


            </div>
        <% end %>
    <% end %>
        </div>
    </div>

</div>

<style>
#guildstones .modal-container.general{
    background-color:transparent;
}
.general-view{
    padding:20px;
    display: flex;
    flex-direction: column;
}
.general-view .general-rows{
    display: flex;
    align-items: center;
padding:10px;

    justify-content: space-between;
}
.general-view .general-rows:nth-child(even) {
    background-color: #bef4c2;
}

.general-view .general-rows:nth-child(odd) {
    background-color: #dadada;
}
.general-header{
    background-color:white;
    border:1px solid black;
    justify-content: space-between;
    display:flex;
    padding:0px 8px;
}
</style>

app/views/guildstones/_modal-all_nominations.html.erb
<div draggable="true" class="guildstone-modal org_chart" 
<% if i > 0 %>
style="transform: translate(
    calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
    z-index: <%= i %>"
<%end%> >
    <div class="section-window-header">    
    All Nominations
        <%= link_to "", close_state_window_path(window: 'allNominations-Guildstone', task: @current_task.id), class:'close-btn windowed' %>
    </div>
    <div class="modal-container general">
        <div class="position-header">
        All nominations available
        </div>
        <div class="general-view">
            <div class="general-header">
                <div>TITLE</div>
                <div>USERNAME</div>
                <div>DEPARTMENT</div>
                <div></div>
            </div>
            <% if PositionNomination.all.count > 0 %>

        <% PositionNomination.all.each do |position|  %>
            <div class="general-rows">
            <span><%= position.position.title %></span>
            <p><%= position.nominee.username %></p>
            <p><%= position.position.title %></p>
<div>
                <% unless position.user.id == current_user.id %>
                    <% if position.position.already_voted?(current_user) %>
                        <%= link_to "UnVote", unvote_path(user: current_user, nomination: position) %>
                    <% else %>
                        <%= link_to "Vote", vote_path(user: current_user, nomination: position) %>
                    <% end %>
                <% end %>
</div>

            </div>
        <% end %>
<% end %>
        </div>
    </div>

</div>

<style>
#guildstones .modal-container.general{
    background-color:transparent;
}
.general-view{
    padding:20px;
    display: flex;
    flex-direction: column;
}
.general-view .general-rows{
    display: flex;
    align-items: center;
padding:10px;

    justify-content: space-between;
}
.general-view .general-rows:nth-child(even) {
    background-color: #bef4c2;
}

.general-view .general-rows:nth-child(odd) {
    background-color: #dadada;
}
.general-header{
    background-color:white;
    border:1px solid black;
    justify-content: space-between;
    display:flex;
    padding:0px 8px;
}
</style>

app/views/guildstones/_modal-org_chart.html.erb
<div draggable="true" class="guildstone-modal org_chart" 
    <% if i > 0 %>
    style="transform: translate(
        calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
        z-index: <%= i %>"
    <%end%> >
        <div class="section-window-header">    
        Altama Energy Org Chart
            <%= link_to "", close_state_window_path(window: 'orgChart-Guildstone', task: @current_task.id), class:'close-btn windowed' %>
        </div>
        <div class="modal-container">
            <div class="position-header">
            Altama Energy Org Chart
            </div>
            <div class="modal-body">
                <div class="chart-container">
                    <span class="whitebackground">Partners</span>
                    <div class="chart-body">
                        <div class="executive">
                            <% @executive_departments.each do |department| %>
                                
                                <% if department.department_type == "faculty"  %>
                                    <div class="exec-department circle">
                                        <%= department.title %>
                                    </div>
                                <% end %>
                            <% end %>

                            <div class="governing">
                                <% @governing_departments.each do |department| %>
                                    
                                        <% unless department.title == "CEO"  %>
                                        <div class="exec-department rounded">
                                            <%= department.title %>
                                        </div>
                                        <% else %>
                                            <div class="exec-department">
                                                <%= department.title %>
                                            </div>
                                        <% end %>                                    
                                <% end %>
                                </div>

                                
                            <% @audit_departments.each do |department| %>                            
                                <div class="exec-department">
                                    <%= department.title %>
                                </div>
                            <% end %>
                            

       

                        </div>

                    <div class="context-menu directors" data-guildstone-target="menu">
                
                        <% @director_departments.each do |department| %>
                                <div class="director-department">
                                <%= department.title %>
                                </div>
                                <div class="department-container" 
                                data-action="click->guildstone#toggleMenu"
                                data-department-id="<%= department.id %>">
                            
                                <!-- Content -->
                            
                                    <div class="context-menu" data-guildstone-target="menu" style="display: none;">
                                    <!-- The user list will be populated here -->
                                    </div>
                                </div>
                            <% end %>
                        </div>
                        <div class="flightcrews">
                        <% @worker_departments.each do |department| %>
                            <div class="flightcrew_department">
                            <%= department.title %>
                            </div>
     
                        <% end %>
                     </div>

                    </div>
                    <span class="whitebackground">Member Owners</span>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.context-menu {
  display: none;
  position: absolute;
  background-color: white;
  border: 1px solid black;
  padding: 10px;
}

.context-menu.active {
  display: block;
}
</style>

app/views/guildstones/_modal-position.html.erb
<div draggable="true" class="guildstone-modal" 
<% if i > 0 %>
style="transform: translate(
    calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
    z-index: <%= i %>"
<%end%> >
<div class="section-window-header"><%= position.title %> 
    
    <%= link_to "", close_position_window_path(window: position.title), class:'close-btn windowed' %>
    
    </div>
    <div class="position-container">
        <div class="position-header">
         <% if  position.user_position  %> <%= position.position_username  %><% else %> Apply today for <%= position.title %><% end %> 
        </div>
        <div class="position-body">
            <div class="position-action">
            Department: <%=position.department.title %>
            <% if  position.user_position  %> 
                <div class="position-row">Employee ID:  </div>
                <div class="position-row">Last Name:   First Name:</div>
                <div class="position-row">Title:  </div>
                <div class="position-row">Extension:  </div>
                <div class="position-row">Hire Date:  <%= position.user_position.created_at  %> </div>
            <% end %>
                <hr />

                
                <div class="election-container">
                    Total votes: <%= position.total_votes %>
                    <br />
                    Votes needed: <%=(@altama_users.count * 0.66666).ceil %>
                    <% if position.term_start %>
                    <br />
                    
                        Term end:  <%= ((position.term_start || Date.today) + (position.term_length_days || 0).days).strftime('%B %d, %Y') %>
                    <br />
                        Term start: <%= position.term_start.strftime('%B %d, %Y') %>
                        <% end %>
                    <br />
                    <% if position.term_start  && position.term_start > Time.now %> 
                        Voting is open
                    <% end %>
                </div>
              

                <div class="buttons">
                    <% unless position.user_position || position.nomination(current_user.id)  %>
                        <%= form_with(model: PositionNomination) do |form| %>
                            <%= form.hidden_field :position_id, :value => position.id %>
                            <%= form.hidden_field :nominee_id, :value => current_user.id%>
                            <%= form.label :campaign_description, "Campaign Description:" %>
                            <br/>
                            <%= form.text_area :campaign_description %>
                            <br/>
                            <%= form.label :resume, "Resume: " %>
                            <br/>
                            <%= form.text_area :resume %>
                            <br/>
                            <%= form.submit 'Apply' %>
                        <% end %>
                    <% end %>
                    <% if position.user_position?(current_user.id) %>
                        This is already your current position!
                    <% elsif position.nomination(current_user.id) %>
                        You have already applied/been nominated for this position!
                        <br>
                        <%= button_to "Cancel Nomination/Application", position_nomination_path(position.nomination(current_user.id)), method: :delete %>
                        
                    <% end %>
                </div>
            </div>
            <% unless  position.user_position  %>
                <div class="position-applications">                
                    <div class="header-title">
                        <span>
                        Applicant
                        </span>
                        <span>
                        Action
                        </span>
                    </div>
                    <div class="application-table">
                    
                        <% position.applications.each do | application | %>
                            
                            <span><%= application.nominee.username %><% if application.user.id == current_user.id %> - <%= application.total_votes %><% end %></span>
                                <% unless application.user.id == current_user.id %>
                                <% unless position.already_voted?(current_user) %>
                                <%= link_to "Vote", vote_path(user: current_user, nomination: application) %>
                                    
                                <% else %>
                                Voted
                                <%#= link_to "UnVote", unvote_path(user: current_user, nomination: application) %>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/guildstones/_modal_rules.html.erb
<div draggable="true" class="guildstone-modal" 
  <% if i > 0 %>
    style="transform: translate(
      calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
      z-index: <%= i %>"
  <%end%> 
 >
  <div class="section-window-header">
    Rules
    <%= link_to "", close_rules_window_path(window: "Rules"), class:'close-btn windowed' %> 
  </div>

<div class="position-body">
    <div class="position-applications">                
        <div class="header-title">
            <span>
            Rule 
            </span>
            <span>
            Action
            </span>
        </div>
          <div class="application-table">
                        <% @rule_proposals.each do | rule_proposal | %>
                            <span><%= rule_proposal.title %></span>
                                <% unless rule_proposal.user.id == current_user.id %>
                                <% if rule_proposal.already_voted?(current_user) %>
                                    <%= link_to "UnVote", unvote_path(user: current_user, rule_proposal: rule_proposal) %>
                                <% else %>
                                    <%= link_to "Vote", vote_path(user: current_user, rule_proposal: rule_proposal) %>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
    </div>
    </div>

</div>
  

app/views/guildstones/_modal_user_positions.html.erb
<div draggable="true" class="guildstone-modal" 
  <% if i > 0 %>
    style="transform: translate(
      calc(-50% + <%= i + 1.5 %>%),calc(-30% + <%= i + 2 %>%));
      z-index: <%= i %>"
  <%end%> 
 >
  <div class="section-window-header">
    UserPositions
    <%= link_to "", close_user_position_window_path(window: "UserPositions"), class:'close-btn windowed' %> 
  </div>

  <% for users in User.all %>
    <div class="name"><%= users.username %></div>
    <div class="positions">
      <% for positions in UserPositionHistory.where(user_id: users.id).where.not(title: nil) %>
        <div class="item">
         <%= positions.title %> 
         <% if positions.active %>
         || Current Position 
         <% end %>
         <% for nonconfs in NonConfidence.where(user_position_id: positions.id) %>
         <br>
         <small>
         There is a proposal for Non Confidence for this user's position. You can vote to pass the non-confidence vote here.
        </small>
        <br>
         <% if nonconfs.already_voted?(current_user) %>
         <small>
         You have already voted to pass this non-confidence vote. You can un-vote here.
         <br>
         <%= link_to "UnVote", unvote_path(user: current_user, non_confidence: nonconfs) %>
         <% else %>
         <%= link_to "Vote", vote_path(user: current_user, non_confidence: nonconfs) %>
         <% end %>
         <% end %>
        </div>
      <% end%>
      </div>
  <% end %>
    

</div>

app/views/guildstones/_rule_category_form.html.erb
 <%= form_with(model: category, :html => {:id => 'rule_category_form', :style => 'display:none;' }) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<span class="testingcat">
  New Category: <%= form.text_field :name %>
  </span>
  <%= form.submit "Create new category", id: 'category_submit'  %>

<%#= button_tag t('buttons.cancel'), type: "submit", name: "cancel", class:'cta red', value: true %>
<% end %>

app/views/guildstones/edit.html.erb
<h1>Editing guildstone</h1>

<%= render "form", guildstone: @guildstone %>

<br>

<div>
  <%= link_to "Show this guildstone", @guildstone %> |
  <%= link_to "Back to guildstones", guildstones_path %>
</div>

app/views/guildstones/new.html.erb
<h1>New guildstone</h1>

<%= render "form", guildstone: @guildstone %>

<br>

<div>
  <%= link_to "Back to guildstones", guildstones_path %>
</div>

app/views/guildstones/old.erb
<% @department = Department.find_by_id(attribute) %>

    <div class="position-container">

        <div class="position-body">
      

        Apply today for positions in the <%= @department.title %>


        <div class="department-position-list">
            List of all positions:
            <% @department.positions.each do |position|  %>
                <%= position.title %>
            <% end %>
        </div>

        </div>
    </div>

app/views/guildstones/old.html.erb
<% @department = Department.find_by_id(attribute) %>

    <div class="position-container">

        <div class="position-body">
      

        Apply today for positions in the <%= @department.title %>


        <div class="department-position-list">
            List of all positions:
            <% @department.positions.each do |position|  %>
                <%= position.title %>
            <% end %>
        </div>

        </div>
    </div>